version: '3.0'

services:
  web:
    image: azuracast/azuracast_web:latest
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    environment: &default-environment
      APPLICATION_ENV: "production" # "production" or "development"
      MYSQL_HOST: "mariadb"         # Change this if you plan to connect to an external DB host.
      MYSQL_PORT: 3306              # ^
      MYSQL_USER: "azuracast"       # Once the database has been installed, don't change this.
      MYSQL_PASSWORD: "*********"   # ^
      MYSQL_DATABASE: "azuracast"   # ^
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      AZURACAST_DC_REVISION: 2      # Only modified when this Docker Compose file has changed.
    volumes:
      - www_data:/var/azuracast/www
      - tmp_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations
      - /mnt/azmedia:/var/azuracast/music
    restart: always

  nginx:
    image: azuracast/azuracast_nginx:latest
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web
      - stations
    volumes:
      - www_data:/var/azuracast/www
      - nginx_letsencrypt_certs:/etc/nginx/ssl
      - nginx_letsencrypt_www:/var/www/letsencrypt
    restart: always

  # To use the LetsEncrypt support:
  # docker-compose run --rm letsencrypt certonly --webroot -w /var/www/letsencrypt
  letsencrypt:
    image: certbot/certbot
    command: /bin/true
    volumes:
      - nginx_letsencrypt_certs:/etc/letsencrypt
      - nginx_letsencrypt_www:/var/www/letsencrypt

  mariadb:
    image: azuracast/azuracast_db:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      << : *default-environment
    restart: always

  influxdb:
    image: azuracast/azuracast_influxdb:latest
    volumes:
      - influx_data:/var/lib/influxdb
    restart: always

  redis:
    image: azuracast/azuracast_redis:latest
    restart: always

  cron:
    container_name: azuracast-cron
    image: azuracast/azuracast_web:latest
    volumes:
      - www_data:/var/azuracast/www
      - tmp_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations
      - /mnt/azmedia:/var/azuracast/music
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    environment:
      << : *default-environment
    command: 'cron'
    restart: always

  cli:
    image: azuracast/azuracast_web:latest
    volumes:
      - www_data:/var/azuracast/www
      - tmp_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations
      - /mnt/azmedia:/var/azuracast/music
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    environment:
      << : *default-environment
    user: 'azuracast'
    working_dir: '/var/azuracast/www'
    command: 'bash'
    tty: true # Pretty colors

  stations:
    container_name: azuracast-stations
    image: azuracast/azuracast_stations:latest
    ports:
    - '8000:8000'
    - '8005:8005'
    - '8006:8006'
    - '8010:8010'
    volumes:
     - station_data:/var/azuracast/stations
     - nginx_letsencrypt_certs:/etc/nginx/ssl:ro
     - /mnt/azmedia:/var/azuracast/music
    restart: always

volumes:
  nginx_letsencrypt_certs: {}
  nginx_letsencrypt_www: {}
  db_data: {}
  influx_data: {}
  station_data: {}
  www_data: {}
  tmp_data: {}
